### ISSUE TITLE
Unable To Get it running, npm run install throws error

### ISSUE THREAD

**Issue by dilkushpatel** [sqlhabit/sql_schema_visualizer#10]
When I run npm run install i get below error

npm ERR! Missing script: "install"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm uninstall # Remove a package
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

On npm run reset I get below error
> sql_schema_visualizer@1.3.2 reset
> bin/reset

'bin' is not recognized as an internal or external command,
operable program or batch file.

I'm running this on windows 11 cmd prompt

**Comment by makaroni4** [comment]
Hey @dilkushpatel 👋 

Oh, great spot – it should be `npm install` 🙈 

Updated the README: https://github.com/sqlhabit/sql_schema_visualizer?tab=readme-ov-file#step-1-clone-and-set-up-the-repo 🙌

**Comment by dilkushpatel** [comment]
What about issue with npm run reset?

It looks like it is not working with window file structure?
