### ISSUE TITLE
Error while running "npm run reset"

### ISSUE THREAD

**Issue by dilkushpatel** [sqlhabit/sql_schema_visualizer#11]
When I run npm run reset I get below error

sql_schema_visualizer@1.3.2 reset
bin/reset

'bin' is not recognized as an internal or external command,
operable program or batch file.

I'm running this on windows 11 cmd prompt

I tried changing bin/reset to bin\\reset but error remains same

**Comment by dilkushpatel** [comment]
@makaroni4 I was able to fix the issue
updated package.json with below details

"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build && node ./bin/create_db_pages",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "reset": "node ./bin/reset",
    "import": "node ./bin/import"
  }

**Comment by makaroni4** [comment]
Awesome, thank you for posting the solution @dilkushpatel 🙌
