### ISSUE TITLE
Pre-render each schema file for deployment to Github Pages

### ISSUE THREAD

**Issue by makaroni4** [sqlhabit/sql_schema_visualizer#5]

**Comment by Hideer** [comment]
Error reported when clicking table in demo and pressing delete key

@makaroni4 
![image](https://user-images.githubusercontent.com/31301552/231416126-cceaabaf-3bf6-4a8e-842e-c7d28f254028.png)

**Comment by makaroni4** [comment]
Hi @Hideer 👋 

Ohhh true, nice catch! I didn't really plan to support edge deletion, since edges are pre-configured. If you're in for a PR to fix it (maybe disable deletion) – I'd be happy to review and merge it 🙌
