### ISSUE TITLE
Standalone component

### ISSUE THREAD

**Issue by tflanagan** [sqlhabit/sql_schema_visualizer#9]
Have you given any thought to providing this as an installable, standalone component that can be embedded in another react project?

**Comment by makaroni4** [comment]
Hi @tflanagan 👋 

Not really tbh, I built the visualizer specifically [for SQL Habit](https://www.sqlhabit.com/datasets/bindle). I thought everyone would use it the same way – export their DB schema, add descriptions and publish it as a documentation website.

💡 Visualizer itself is [already a React component](https://github.com/sqlhabit/sql_schema_visualizer/blob/main/src/Visualizer/index.tsx#L334), it just expects the DB data in a specific format. 

Ping me if I can help with anything 🙏
